#ifndef _oarrow_H_
#define _oarrow_H_

enum
{
    Oarrow                        = 1000,
    OARROW_TARGET,
    OARROW_TARGET_OFFSET,
    OARROW_LENGTH,
    OARROW_FLAT_ENABLE,
    OARROW_ROTATION_SEGMENTS,
    OARROW_FLAT_ORIENTATION,
    OARROW_FLAT_ORIENTATION_XP    = 0,
    OARROW_FLAT_ORIENTATION_XN,
    OARROW_FLAT_ORIENTATION_YP,
    OARROW_FLAT_ORIENTATION_YN,
    OARROW_FLAT_ORIENTATION_ZP,
    OARROW_FLAT_ORIENTATION_ZN,
	OARROW_BASE                   = 2000,
    OARROW_BASE_RADIUS,
    OARROW_TIP                    = 3000,
    OARROW_TIP_RADIUS,
    OARROW_TIP_LENGTH
};

#endif