CONTAINER oarrow
{
	NAME Oarrow;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL OARROW_LENGTH				{ UNIT METER; MIN 0.0; }
		LONG OARROW_ROTATION_SEGMENTS 	{ MIN 3; MAX 100; }
	}

	INCLUDE Oprimitiveaxis;

	GROUP OARROW_BASE
	{
		DEFAULT 1;
		REAL OARROW_BASE_RADIUS			{ UNIT METER; MIN 0.0; }
	}

	GROUP OARROW_TIP
	{
		DEFAULT 1;

		REAL OARROW_TIP_RADIUS			{ UNIT METER; MIN 0.0; }
		REAL OARROW_TIP_LENGTH			{ UNIT METER; MIN 0.0; }
	}

	GROUP OARROW_BEVEL
	{
		DEFAULT 1;

		BOOL OARROW_BEVEL_ENABLE		{ }		
		REAL OARROW_BEVEL_RATIO       	{ UNIT PERCENT; MIN 0.0; CUSTOMGUI REALSLIDER; MINSLIDER 0.0; MAXSLIDER 100.0; }
	}
}